version: '3.8'
services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - web

networks:
  web:
    driver: bridge